services:
  - type: web
    name: safespace-api
    env: java
    region: oregon
    plan: free
    buildCommand: "./mvnw clean package -DskipTests"
    startCommand: "java -jar target/safespace-0.0.1-SNAPSHOT.jar"
    envVars:
      - key: JWT_SECRET
        value: secret
      - key: ACTIVE_PROFILE
        value: prod
