package br.com.fiap.safespace.model;

public enum AtendimentoType {
    PSICOLOGICO_EMERGENCIAL,
    APOIO_EMOCIONAL,
    TRIAGEM_INICIAL,
    ENCAMINHAMENTO_CLINICO,
    POS_CRISE,
    ORIENTACAO_FAMILIAR,
    ESCUTA_ATIVA,
    MINDFULNESS,
    VIRTUAL,
    PRESENCIAL;
}
